### ISSUE TITLE
please

### ISSUE THREAD

**Issue by zyohhh** [hua-ops/bearingPlatform_hua#1]
请问本地诊断正常数据一直显示内圈故障是怎么回事？

**Comment by hua-ops** [comment]
这应该是因为在训练模型时，对训练集进行了标准化等操作，但是在使用测试数据进行本地诊断时，测试数据的标准化操作不是以训练集的标准化尺度进行的，也就是训练集和测试集的标准化尺度不一致。所以在对训练集进行标准化时，需要将训练集的标准化尺度参数等以一个配置文件等的形式记录下来，然后在调用模型进行本地诊断时，同时加载配置文件，并以相同的标准化尺度对测试数据进行标准化操作。
在`data_preprocess.py `的179行左右有简单说明

**Comment by zyohhh** [comment]
搞定😀
